<a href="https://colab.research.google.com/github/kabil1001/DS_Codes/blob/main/Data_Aggregation_Using_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

In [23]:
swiggy_data = pd.read_csv('https://raw.githubusercontent.com/kabil1001/DS_Codes/main/Dataset/swiggy.csv')

In [24]:
swiggy_data.head(2)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56

In [25]:
swiggy_data.shape

(8680, 10)

In [26]:
swiggy_data.columns

Index(['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg ratings',
       'Total ratings', 'Food type', 'Address', 'Delivery time'],
      dtype='object')

In [30]:
swiggy_data['Delivery time'].mean()

53.96705069124424

In [31]:
# Grouped Objects

# When you apply certain  aggregation function to each group seperately then we do grouping

# Number of groups  which is created will be equal to the unique values of the grouping column

In [35]:
swiggy_data.head(2)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56

In [38]:
swiggy_data['City'].nunique()

9

In [52]:
# Avg_price - output column name (custom), ('Price'-> Column to agg, np.mean -> func to apply)
# we can inbuilt, third party package function,& userdefined function
# Mulitple  fields can be used to group the dataframe

result_1 = swiggy_data.groupby(['City']).agg(
                                  total_count_order = ('ID', 'count'),
                                  Avg_Price = ('Price', np.mean),
                                  Avg_Delivery_Time = ('Delivery time', np.mean),
                                  Avg_Delivery_Time_hr = ('Delivery time', lambda x:  np.mean(x/60))).reset_index()

In [55]:
result_1.loc[result_1['total_count_order'] == result_1['total_count_order'].max()]

,City,total_count_order,Avg_Price,Avg_Delivery_Time,Avg_Delivery_Time_hr
5,Kolkata,1346,362.294205,67.809807,1.130163

In [58]:
result_2 = swiggy_data.groupby(['City','Food type']).agg(Count_order = ('ID','count')).reset_index()

In [67]:
bangalore_result = result_2.loc[result_2['City'] == 'Bangalore']

bangalore_result.loc[bangalore_result['Count_order'] == bangalore_result['Count_order'].max()]

          City     Food type  Count_order
977  Bangalore  South Indian           32

In [65]:
result_2.loc[result_2['City'] == 'Bangalore'].sort_values(by  =['Count_order'], ascending= False)

           City                           Food type  Count_order
977   Bangalore                        South Indian           32
740   Bangalore                              Indian           27
844   Bangalore                        North Indian           25
560   Bangalore                             Chinese           21
650   Bangalore                            Desserts           15
...         ...                                 ...          ...
625   Bangalore  Chinese,Tibetan,Nepalese,Pan-Asian            1
626   Bangalore                Chinese,Tibetan,Thai            1
627   Bangalore                 Coastal,Goan,Indian            1
628   Bangalore                     Coastal,Seafood            1
1041  Bangalore                     Turkish,Arabian            1

[645 rows x 3 columns]

In [16]:
df = pd.DataFrame([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [np.nan, np.nan, np.nan]],
                                  columns=['A', 'B', 'C'])